# Generated by Django 4.2.28 on 2026-02-19 18:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(choices=[('yaounde', 'Yaoundé'), ('douala', 'Douala'), ('bafoussam', 'Bafoussam'), ('bamenda', 'Bamenda'), ('garoua', 'Garoua'), ('maroua', 'Maroua'), ('ngaoundere', 'Ngaoundéré'), ('bertoua', 'Bertoua'), ('ebolowa', 'Ebolowa'), ('kribi', 'Kribi'), ('limbe', 'Limbé'), ('buea', 'Buéa'), ('kumba', 'Kumba'), ('dschang', 'Dschang'), ('nkongsamba', 'Nkongsamba'), ('edea', 'Edéa'), ('mbalmayo', 'Mbalmayo'), ('sangmelima', 'Sangmélima'), ('meiganga', 'Meiganga'), ('kousseri', 'Kousséri')], max_length=100)),
                ('superficie_m2', models.PositiveIntegerField()),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain'), ('local_commercial', 'Local commercial')], max_length=30)),
                ('disponible', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locataire_nom', models.CharField(max_length=120)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('caution', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='immobilier.bienimmobilier')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='immobilier.proprietaire'),
        ),
    ]
