# Generated by Django 4.2.28 on 2026-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_proprietaire_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='contrat_modele',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='exige_validation_contrat',
            field=models.BooleanField(default=False),
        ),
    ]
