# Generated by Django 4.2.28 on 2026-02-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_bienimmobilier_contrat_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='contrat_fichier',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
    ]
