# Generated by Django 4.2.28 on 2026-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_bienimmobilier_contrat_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienimmobilier',
            name='contrat_fichier',
        ),
        migrations.RemoveField(
            model_name='bienimmobilier',
            name='contrat_modele',
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='locataire_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='locataire_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='locataire_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
