# Generated by Django 6.0.2 on 2026-02-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='ville',
            field=models.CharField(choices=[('yaounde', 'Yaoundé'), ('douala', 'Douala'), ('bafoussam', 'Bafoussam'), ('bamenda', 'Bamenda'), ('garoua', 'Garoua'), ('maroua', 'Maroua'), ('ngaoundere', 'Ngaoundéré'), ('bertoua', 'Bertoua'), ('ebolowa', 'Ebolowa'), ('kribi', 'Kribi'), ('limbe', 'Limbé'), ('buea', 'Buéa'), ('kumba', 'Kumba'), ('dschang', 'Dschang'), ('nkongsamba', 'Nkongsamba'), ('edea', 'Edéa'), ('mbalmayo', 'Mbalmayo'), ('sangmelima', 'Sangmélima'), ('meiganga', 'Meiganga'), ('kousseri', 'Kousséri')], max_length=100),
        ),
    ]
