# Generated by Django 6.0.2 on 2026-02-19 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_alter_bienimmobilier_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='loyer_mensuel',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='caution',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
