# Generated by Django 6.0.2 on 2026-02-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_alter_bienimmobilier_loyer_mensuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='immobilier.bienimmobilier')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
